name: GitHub CI Builder

on:
  workflow_dispatch:
    inputs:
      os_target:
        description: 'Choose the OS to build for'
        required: true
        default: 'ubuntu'
        type: choice
        options:
          - ubuntu
          - macos

  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ inputs.os_target == 'macos' && 'macos-latest' || 'ubuntu-22.04' }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Build Tag
        id: set_tag
        run: |
          export TAG="v$(date +'%Y%m%d-%H%M')"
          echo "TAG_NAME=$TAG" >> $GITHUB_ENV
          echo "tag_name=$TAG" >> $GITHUB_OUTPUT

      - name: Set Git Identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Git Tag
        run: |
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Make Script Executable
        run: |
          chmod +x ./build_adventurecoin_ubuntu.sh
          chmod +x ./build_adventurecoin_mac.sh

      - name: Install Dependencies (Ubuntu)
        if: inputs.os_target == 'ubuntu'
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Run Ubuntu Build
        if: inputs.os_target == 'ubuntu'
        run: |
          echo -e "2\ny\ny\ny\ny\ny" | ./build_adventurecoin_ubuntu.sh

      - name: Install Protobuf (macOS)
        if: inputs.os_target == 'macos'
        run: |
          brew install protobuf@3
          echo 'PATH="/opt/homebrew/opt/protobuf@3/bin:$PATH"' >> $GITHUB_ENV
          echo 'LDFLAGS="-L/opt/homebrew/opt/protobuf@3/lib $LDFLAGS"' >> $GITHUB_ENV
          echo 'CPPFLAGS="-I/opt/homebrew/opt/protobuf@3/include $CPPFLAGS"' >> $GITHUB_ENV
          echo 'PKG_CONFIG_PATH="/opt/homebrew/opt/protobuf@3/lib/pkgconfig:$PKG_CONFIG_PATH"' >> $GITHUB_ENV

      - name: Run macOS Build
        if: inputs.os_target == 'macos'
        run: |
          echo -e "2\ny\ny" | ./build_adventurecoin_mac.sh

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: AdventureCoin ${{ env.TAG_NAME }}
          generate_release_notes: true
          files: |
            ./compiled_wallets/*
            ./compiled_wallets_macos/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
