name: GitHub CI Builder

on:
  workflow_dispatch:
    inputs:
      os_target:
        description: 'Choose the OS to build for'
        required: true
        default: 'ubuntu'
        type: choice
        options:
          - ubuntu
          - macos

  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ inputs.os_target == 'macos' && 'macos-latest' || 'ubuntu-22.04' }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Build Tag
        id: set_tag
        run: |
          export TAG="v$(date +'%Y%m%d-%H%M')"
          echo "TAG_NAME=$TAG" >> $GITHUB_ENV
          echo "tag_name=$TAG" >> $GITHUB_OUTPUT

      - name: Set Git Identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Git Tag
        run: |
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Make Script Executable
        run: |
          chmod +x ./build_adventurecoin_ubuntu.sh
          chmod +x ./build_adventurecoin_mac.sh

      - name: Install Dependencies (Ubuntu)
        if: inputs.os_target == 'ubuntu'
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Run Ubuntu Build
        if: inputs.os_target == 'ubuntu'
        run: |
          echo -e "2\ny\ny\ny\ny\ny" | ./build_adventurecoin_ubuntu.sh

      - name: Run macOS Build
        if: inputs.os_target == 'macos'
        run: |
          # Set up and build Protobuf 3.6.1
          export PROTOBUF_DIR="$HOME/local/protobuf-3.6.1"
          mkdir -p "$PROTOBUF_DIR"
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protobuf-cpp-3.6.1.tar.gz
          tar -xzf protobuf-cpp-3.6.1.tar.gz
          cd protobuf-3.6.1
          ./configure --prefix="$PROTOBUF_DIR"
          make -j$(sysctl -n hw.logicalcpu)
          make install
          cd ..

          # Export environment variables
          export PKG_CONFIG_PATH="$PROTOBUF_DIR/lib/pkgconfig:$PKG_CONFIG_PATH"
          export LDFLAGS="-L$PROTOBUF_DIR/lib $LDFLAGS"
          export CPPFLAGS="-I$PROTOBUF_DIR/include $CPPFLAGS"
          export LD_LIBRARY_PATH="$PROTOBUF_DIR/lib:$LD_LIBRARY_PATH"
          export PATH="$PROTOBUF_DIR/bin:$PATH"
          export PROTOC="$PROTOBUF_DIR/bin/protoc"

          # Confirm protobuf installed
          $PROTOC --version
          pkg-config --modversion protobuf || echo "pkg-config failed"

          # Run the macOS build script
          echo -e "2\ny\ny" | ./build_adventurecoin_mac.sh

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: AdventureCoin ${{ env.TAG_NAME }}
          generate_release_notes: true
          files: |
            ./compiled_wallets/*
            ./compiled_wallets_macos/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
